# -*- coding: utf-8 -*-
"""main

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zDm8WcmJL4jZhOa83AXgxeWY5ECaHOub
"""
!pip install pytelegrambotapi

import telebot
from telebot import types
from datetime import datetime
import matplotlib.pyplot as plt

MY_TOKEN = "8590324035:AAEIFPKl9zXyXfoch3zGNIG3yT8bvwB_4-0"

bot = telebot.TeleBot(MY_TOKEN)

user_expenses = {}
user_savings = {}

CATEGORIES = {
    "еда": "Food",
    "food": "Food",
    "кофе": "Food",
    "coffee": "Food",
    "restaurant": "Food",
    "кафе": "Food",
    "transport": "Transport",
    "транспорт": "Transport",
    "taxi": "Transport",
    "такси": "Transport",
    "bus": "Transport",
    "автобус": "Transport",
    "metro": "Transport",
    "entertainment": "Entertainment",
    "развлечения": "Entertainment",
    "movie": "Entertainment",
    "кино": "Entertainment",
    "games": "Entertainment",
    "sport": "Sport",
    "спорт": "Sport",
    "gym": "Sport",
    "fitness": "Sport",
    "education": "Education",
    "учеба": "Education",
    "books": "Education",
    "course": "Education",
    "clothes": "Clothes",
    "одежда": "Clothes",
    "shoes": "Clothes",
    "health": "Health",
    "здоровье": "Health",
    "medicine": "Health",
    "shopping": "Shopping",
    "shop": "Shopping",
    "магазин": "Shopping",
    "bills": "Bills",
    "internet": "Bills",
    "коммуналка": "Bills",
    "other": "Other",
    "другое": "Other"}

def get_current_month():
    return datetime.now().strftime("%B")
    
def normalize_category(category):
    category = category.lower().strip()
    return CATEGORIES.get(category,"Other")

